name: CD - Full Project Deployment

on:
  workflow_dispatch:   # manual one-click deploy
  push:
    branches:
      - main           # optional: auto-deploy when infra repo updates

jobs:
  deploy:
    runs-on: self-hosted   # runner with kubectl + kubeconfig

    steps:
      # Checkout infra repo
      - name: Checkout infra repo
        uses: actions/checkout@v4

      # 1️⃣ Deploy infra components (metrics server, ingress controller)
      - name: Deploy infra components
        run: |
          kubectl apply -f first/
          # if metrics-server is inside kube-system
          kubectl rollout status deployment/metrics-server -n kube-system || true

      # 2️⃣ Checkout and deploy Frontend
      - name: Checkout Frontend
        uses: actions/checkout@v4
        with:
          repository: USER-POLYGLOT/frontend
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Deploy Frontend
        run: |
          kubectl apply -f kubernetes/
          kubectl rollout status deployment/frontend-deployment

      # 3️⃣ Checkout and deploy Backend
      - name: Checkout Backend
        uses: actions/checkout@v4
        with:
          repository: USER-POLYGLOT/backend
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Deploy Backend
        run: |
          kubectl apply -f kubernetes/
          kubectl rollout status deployment/backend-deployment

      # 4️⃣ Checkout and deploy AI Service
      - name: Checkout AI Service
        uses: actions/checkout@v4
        with:
          repository: USER-POLYGLOT/ai
          token: ${{ secrets.GH_PAT }}
          ref: main

      - name: Deploy AI Service
        run: |
          kubectl apply -f kubernetes/
          kubectl rollout status deployment/ai-deployment
